#!/usr/bin/perl

#
# for this to work, perl module needs to be installed.
# in ubuntu run
#
# sudo apt-get install libapache2-mod-perl2
# sudo apache2ctl restart
# sudo  a2enmod perl
# These scripts print to  /var/log/apache2/error.log

package ReceiveFirstCommand;
use strict;

use Apache2::RequestIO (); 
use Apache2::RequestUtil (); 
use Apache2::RequestRec (); 
use Apache2::Log (); 

use Apache2::Const -compile => qw(OK DECLINED :log); 
#use Apache2::Const -compile => qw(OK);

sub handler { 
    my $r = shift; 

    # handle POST requests 
    if ( $r->method() eq "POST" ) { 

        # create a post data buffer 
        my $PostBuffer = ''; 

        # loop over each line of data 
        $r->log->notice("RootPATest.first: Post Command Received. Data:"); 
        while($r->read($PostBuffer, 1024)) { 
            $r->log->notice("'$PostBuffer'"); 
        } 

	    $r->content_type('text/plain');
	    
	    print "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> \
	    <ContentManagementRequest xmlns=\"http://www.mcore.gi-de.com/2012/04/schema/EnrollmentService\">\
		<commands>
		    <command id=\"1\" type=\"CMP\" ignoreError=\"true\">\
		        <commandValue>AgAAAKQAAAAAAAAA7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMw=</commandValue>
		    </command>
		    <command id=\"2\" type=\"CMP\" ignoreError=\"true\">\
		        <commandValue>AAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyA=</commandValue>
		    </command>
		    <command id=\"3\" type=\"CMP\" ignoreError=\"true\">\
		        <commandValue>CQAAAGQAAAAAAAAABwAAAAAAAAABAQEBAQEBAQEBAgICAgICAgICAgMDAwMDAwMDAwMEBAQEBAQEBAQEBQUFBQUFBQUBAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fIA==</commandValue>
		    </command>
		    <command id=\"4\" type=\"CMP\" ignoreError=\"true\">\
		        <commandValue>HAAAACwAAAAAAAAAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyA=</commandValue>
		    </command>
		    <command id=\"5\" type=\"CMP\" ignoreError=\"true\">\
		        <commandValue>AQAAAA==</commandValue>
		    </command>
		</commands>
	    </ContentManagementRequest>";

    
    }  else {
        $r->log->notice("RootPATest.first: HTTP command was not POST");
            $r->log->notice("RootPATest.first: but $r->method()"); 
    }
    
    return Apache2::Const::OK;
} 

1;




